---
# The template integration allows creating entities which derive their values
# from other data. This is done by specifying templates for properties of an
# entity, like the name or the state.
#
# https://www.home-assistant.io/integrations/template/
#
# This binary sensor is used to determine if the main bath fan is turned on
#
trigger:
  - platform: state
    entity_id: fan.main_bath_fan
    to: "on"
    id: "t1"
  - platform: state
    entity_id: fan.main_bath_fan
    to: "off"

binary_sensor:
  - name: "Main Bath Manual Fan"
    icon: mdi:fan-clock
    state: >
      {% if trigger.id == 't1' and trigger.to_state.context.parent_id is none %}
        on
      {% else %}
        off
      {% endif %}
